### ISSUE TITLE
the application importing error

### ISSUE THREAD

**Issue by haythemmousa** [MarkoGranzin/ApexFlowChart#1]
while trying to import the applicaiton , it gives error , that is not compatible , your application contains call not supported 

iam using apex 18.2

**Comment by MarkoGranzin** [comment]
Sorry, the ducomention here is not as good as it should be.
The plugin region_type_plugin_apex_flow_chart.sql is for apex 19.1 for older versions please use region_type_plugin_apex_flow_chart_APEX_5.1.sql. I will note it explicitly in the text again
